# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/app ./cmd/proxy"
  bin = "tmp/app"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000 # millisecondes de délai avant de recompiler

[log]
  time = true

[watch]
  dirs = ["cmd", "internal", "pkg"]
  exclude = ["tmp", "vendor"]
